require("core.plugin_config.colors")
require("core.plugin_config.harpoon")
require("core.plugin_config.lsp")
require("core.plugin_config.telescope")
require("core.plugin_config.undotree")
require("core.plugin_config.nvimtree_config")
